version: '3'

services:
  mitmiproxy-mobile:
    build: ./mitmiproxy-mobile
    hostname: mitmiproxy-mobile
    privileged: true
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    ports:
        - "8080:8080"
    stdin_open: true
    tty: true
    container_name: mitmproxy-container
    networks:
      - private
      - proxy
    volumes:
      - ./:/data
#    command:
#      - sh -c "ls -l && ls"
#      - whereis mitmdump 
#      - mitmdump  -s /data/fl.py --ssl-insecure --set stream_large_bodies=10m --ignore-hosts '(mzstatic.com|apple.com|icloud.com|mobilesuica.com|crashlytics.com|google-analytics.com|tokyo-ame2.jwa.or.jp)' --anticomp --set block_global=false --set flow_detail=2 &
networks:
  proxy:
    external:
      name: YOUR_EXTERNAL_PROXY_NET_NAME
  private:
    driver: bridge
    internal: true
